algoritmo "trabalho media"
// Função :
// Autor :
// Data : 22/11/2024
// Seção de Declarações 
var
    valor1, valor2, med: real
inicio
// Seção de Comandos
   Escreval("digite o primeiro valor: ")
   Leia(valor1)
   Escreval("digite o segundo valor: ")
   Leia(valor2)
   med <- (valor1 + valor2) /2
   Escreval(" O resultado da media entre ", valor1, " e ", valor2, " é ", med)
fimalgoritmo
